---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170816122823"
generator:
  name: "NewStarterRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.34.0"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "c7ddec0ff638a1cfd019004b18917468d209883d"
    sha: "c7ddec0"

